import { NgModule } from '@angular/core';
import {
  AvatarModule, BoxModule, BrandModule, ButtonModule, CheckboxLinkModule, CheckboxModule, ContainerModule,
  HeaderModule, IconModule, InputModule, LabelModule, OnboardingImageModule, PillModule, StackModule,
  TextModule, ThemeProviderModule, TitleModule, TooltipModule, ImageFeedbackModule, LinkModule, InputOtpModule,
  LayoutModule, FeedbackContentModule, FeedbackModule, SpinnerModule,
  CardModule, ListContentModule, ListSideModule, ListActionsModule, ListTitleModule, ListDescriptionModule,
  ListSubtitleModule, ListAvatarModule, ListModule, ModalModule, ModalHeaderModule, ModalContentModule,
  ModalFooterModule, SelectModule, SkeletonModule, DividerModule, AccordionItemModule, AccordionModule, StackCarouselModule,
  CardBenefitsModule, BannerModule, OptionListGroupModule, OptionListModule, OptionListCardModule, CardBadgeModule,
  InputAmountModule, CardGroupModule, InputDateModule, DatePickerModule, StepsModule, StepsItemModule, CardHeaderModule,
  CardContentModule, CardFooterModule, CardImageModule, CardMoreInfoModule, GridModule, GridItemModule,
  RadioGroupModule,
  radioModule,
  EmptyStateModule,
  TabListModule,
  TabPanelsModule,
  TabPanelModule,
  MenuFooterModule,
  ActivityListModule,
  BadgeModule,
  MenuModule,
  MenuContentModule,
  TabModule,
  TabsModule,
  HeaderOptionsModule,
  HeaderNotifProfileModule,
  CalendarModule,
  CalendarRangeModule,
  CheckboxGroupModule,
  CalloutModule
} from '@kite/angular';

@NgModule({
  exports: [
    AvatarModule,
    BoxModule,
    BrandModule,
    ButtonModule,
    CheckboxLinkModule,
    CheckboxModule,
    ContainerModule,
    HeaderModule,
    IconModule,
    InputModule,
    LabelModule,
    OnboardingImageModule,
    PillModule,
    StackModule,
    TextModule,
    ThemeProviderModule,
    TitleModule,
    TooltipModule,
    ImageFeedbackModule,
    LinkModule,
    InputOtpModule,
    LayoutModule,
    FeedbackContentModule,
    FeedbackModule,
    SpinnerModule,
    CardModule,
    ListContentModule,
    ListSideModule,
    ListActionsModule,
    ListTitleModule,
    ListDescriptionModule,
    ListSubtitleModule,
    ListAvatarModule,
    ListModule,
    ModalModule,
    ModalHeaderModule,
    ModalContentModule,
    ModalFooterModule,
    SelectModule,
    SkeletonModule,
    DividerModule,
    AccordionItemModule,
    AccordionModule,
    StackCarouselModule,
    CardBenefitsModule,
    BannerModule,
    OptionListGroupModule,
    OptionListModule,
    OptionListCardModule,
    CardBadgeModule,
    InputAmountModule,
    CardGroupModule,
    InputDateModule,
    DatePickerModule,
    StepsModule,
    StepsItemModule,
    CardHeaderModule,
    CardContentModule,
    CardFooterModule,
    CardImageModule,
    CardMoreInfoModule,
    GridModule,
    GridItemModule,
    RadioGroupModule,
    radioModule,
    EmptyStateModule,
    TabListModule,
    TabPanelsModule,
    TabPanelModule,
    MenuFooterModule,
    ActivityListModule,
    BadgeModule,
    MenuModule,
    MenuContentModule,
    TabModule,
    TabsModule,
    HeaderOptionsModule,
    HeaderNotifProfileModule,
    CalendarModule,
    CalendarRangeModule,
    CheckboxGroupModule,
    CheckboxLinkModule,
    CheckboxModule,
    CardHeaderModule,
    ModalModule,
    ModalContentModule,
    ModalFooterModule,
    ModalHeaderModule,
    CalloutModule,
    FeedbackContentModule,
    FeedbackModule
  ]
})
export class KiteModule { }
